#!/usr/bin/env bash
# a script that displays FizzBuzz
for ((i=1; i<=100; i=i+1)); do
        if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]; then
                echo "FizzBuzz"
        elif [ $((i % 3)) -eq 0 ]; then
                echo "Fizz"
        elif [ $((i % 5)) -eq 0 ]; then
                echo "Buzz"
        else
                echo $i
        fi
done
