#!/usr/bin/env bash
# A script that displays numbers 1 to 20 with various messages at various specified iterations
count=1

while [[ $count -le 20 ]]; do
        case $count in
                5)      echo "bad luck from China"
                        ;;
                10)     echo "bad luck from Japan"
                        ;;
                18)     echo "bad luck from Italy"
                        ;;
        esac
        echo $count
        count=$((count + 1))
done
