#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes
hour=0
minute=1
while [[ $hour -le 12 ]]; do
        if [ $minute -eq 1 ]; then
                echo "Hour: "$hour
                hour=$((hour + 1))
        fi
        echo $minute
        minute=$((minute + 1))
        if [ $minute -gt 59 ]; then
                echo "Hour: "$hour
                hour=$((hour + 1))
                minute=1
                echo $minute
                minute=$((minute + 1))
        fi
done
