#!/usr/bin/env bash
# configure it to our needs so that you can connect to a server without typing a password
Host 3.238.234.192
 PasswordAuthentication no
 IdentityFile ~/.ssh/school
Host 52.91.151.139
 PasswordAuthentication no
 IdentityFile ~/.ssh/school
